FROM oven/bun:1

WORKDIR /src/app

COPY ./packages ./packages
COPY ./bun.lock  ./bun.lock

COPY ./package.json  ./package.json
COPY ./turbo.json  ./turbo.json

COPY ./apps/front-end  ./apps/front-end

RUN bun install

RUN bun run build


EXPOSE 3000

CMD [ "bun" ,"run" , "start:frontend"]

